### PR TITLE
support input parameters for modules

### PR DESCRIPTION
**Pull request by superstar54**
Since batoms-api is outdated, and not usable for modules likes: bonds and isosurface.  Here is a quick patch for using batoms-api.

@alchem0x2A I realized that you are working on the `develop` branch using a more general approach, so we don't need to merge this PR. Please have a look, maybe you could get some hints.

### CODE REVIEW

**Comment by alchem0x2A** [comment]
yes! the PR seems quite relevant I was implementing. I'm also adding a general schema to allow specifying default types etc. I'm also adding a yaml config loader that shares the same base configs across different atoms objects. Basically I'm adding things like following orders from `render`
1. `batoms_inputs`: initializing parameters for Batoms apart from the atoms itself (note there are several params currently inactive like `model_style`, we can have a quick fix for that in `batoms`)
2. `settings`: all other setter parameters in nested dicts to apply to properties of `Batoms`. I'm trying to make this as general as possible so that the type check / conversion is controlled by the schema. There are some caveats regarding the current `batoms` version, for example `batoms.species.update()` are sometimes not behaving exactly as expected, we can fix that `batoms` later.
3. `post_modifications`: a list of handy python expressions to modify the batoms / scene objects, like the ways `ase run` does. I'll ignore the safety concerns for the time being and let's see if need to strict its use.
4. `render_inputs`: like old way, parameters to insert for the render. User can also provide `settings.render.<property>=<value>` in step2 for general purpose settings like renderer engine, sample size etc
5. *TODO*: can add a few keywords to control the initialization of global blender objects such as lighting and plane in addition to Batoms

Other considerations:
1. User can load a base yaml and provide minimal inputs for rendering similar systems
2. supports checking between the dumped version in input pickle file and current loaded batoms_api, so that input files can be shared between hosts
3. *TODO*: supports hybrid rendering modes. User should be able to do either of the following: I) run `batoms_api` and `batoms` both on host system ii) run `batoms_api` and `batoms` both in container iii) run `batoms_api` on host but render with `batoms` in container (or save input file first and render separately).  


I appreciate if you have anything more to add to the list above! Btw I like your test examples! Will cherry pick this PR into develop branch and submit a new PR soon, prob Wed or Thu

**Comment by alchem0x2A** [comment]
@superstar54 for the sanity of git commits I'll merge `module_input` --> `develop` and send another PR from there.

**Comment by superstar54** [comment]
Sure, please merge.

Very nice implementation in the `develop` branch.

I will fix the `model_style`. Please add issues for other caveats, so that I can fix them. In order to keep parameters in the Batoms `__init__` not too many, parameters like `polyhedra_style` will be removed in the future. 

One comment on the schema. For each module, there are two kinds of parameters. Take `bonds` as an example:
  - normal parameters: `bonds.show_hydrogen_bond`, `bonds.show_search`.
  - collection parameters, which can be repeated and saved in `bonds.setting`. 

So in the schema, bonds will look like this:
```
  bonds:
    show_hydrogen_bond: { _type: _bool }
    show_search: { _type: _bool }
    setting:
      _any:
        _eval_key: true
        min: { _type: _float }
        max: { _type: _float }
        search: { _type: _int }
        order: { _type: _int }
        style: { _type: [_int, _str] }
        polyhedra: { _type: _bool }
```

**Comment by alchem0x2A** [comment]
yeah, the `show_hydrogen_bond` etc are what I'm currently missing! will check again with all the setters available.

**Pull request merged**
