### PR TITLE
General purpose api for batoms using schema

### PR DESCRIPTION
**Pull request by alchem0x2A**
related to #3 but more general solution, see following implementations

1. `schema.yaml` under `batoms_api.api` defines all the legit setters for batoms and its submodules, with minimal type check.
2. `batoms_api.render` can take both default input params (loaded from another yaml) and merge with user-provided settings. Type check and conversion is performed before dumping into pickle file (so no more type check when doing actual rendering)
3. `batoms_api.render` saves current api version to pickle file to avoid conflict when loading on blender side
4. `batoms_api.script_api` is now a loadable submodule in blender. The `run` function handles a single `sys.argv` param as the input file
5. `script_api.run` performs the rendering in following order:

  1 `batoms_inputs`: initializing parameters for Batoms apart from the atoms / volume
  2 `settings`: all other setter parameters in nested dicts to apply to properties of Batoms.  
     If `setting.<prop>.draw` is True, the property will be labeled calls the `prop.draw()` at the end of this step
  3 `post_modifications`: a list of handy python expressions to modify the batoms / scene objects. 
     A general `batoms.draw()` is always called after step 3
  4 `render_inputs`:  parameters to provide to the render

Currently `ribbon` and `magres` are not implemented in the api but should be easy to add them in

### CODE REVIEW

**Comment by alchem0x2A** [comment]
`cli` is not touched at the moment.

@superstar54 You may want to check the files before merging. And some thoughts
1. `schema.yaml` is currently manually generated. Pleas take a look if any important settings are wrong / missing
2. Currently configurations are split into `batoms_input`, `render_input`and general `settings`, taking from previous naming style. It may be more consistent if we can just use 1 setting dict. Most init parameters in `batoms_input` are also setters (except `label` which cannot be post-modified) so it seems doable. Please let me know if your preference
3. What about usage of a general base yaml file as the "basic user settings"? Potentially the user can add every species / bonds setting in the yaml file, and the renderer only picks up species / bonds that exist in current atoms.

**Comment by superstar54** [comment]
Great! I will look at the code.

I agreed that we can use just one setting dict. `batoms_input` is not necessary. 

We can provide the options for the user to set up their own setting, e.g. bonds, color. It's better to add this option into `batoms` instead of `batoms-api`. Thus, the user can also use it both with and without `batoms-api`. In the preference of `batoms`, we can add an option to set up the file path.

I am working on reorganizing the `batoms` code, maybe we can try to auto-generate the `schema.yaml` after that.

**Comment by alchem0x2A** [comment]
Agreed. The general setting is better added at the `batoms` side. One way I can think to generate the schema is to use `inspect` to check all init params and setters of a Batoms-subclass. We can discuss that after the refactor

**Review by superstar54 — APPROVED** [review]
Super!

**Pull request merged**
